import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — GameForge AI",
};

export default function TermsPage() {
  return (
    <section className="py-24 px-4 sm:px-6 lg:px-8 bg-surface-dark">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-heading uppercase text-primary-light mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-neutral-500 mb-10">
          Last updated: March 23, 2026
        </p>

        <div className="space-y-8 text-neutral-400 text-sm leading-relaxed">
          <div>
            <h2 className="text-lg font-semibold text-neutral-200 mb-3">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using GameForge AI, you agree to be bound by these
              Terms of Service. If you do not agree, please do not use our
              service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-neutral-200 mb-3">
              2. Description of Service
            </h2>
            <p>
              GameForge AI provides an AI-powered game creation platform that
              allows users to describe games in natural language and receive
              playable browser-based games generated in real-time.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-neutral-200 mb-3">
              3. Demo Product Disclaimer
            </h2>
            <p>
              This product is currently in a demonstration phase. Features,
              availability, and functionality may change without notice. Demo
              accounts and data may be reset or removed at any time.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-neutral-200 mb-3">
              4. User Accounts
            </h2>
            <p>
              You are responsible for maintaining the confidentiality of your
              account credentials and for all activities that occur under your
              account. You agree to provide accurate information when creating an
              account.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-neutral-200 mb-3">
              5. Generated Content
            </h2>
            <p>
              Games created through GameForge AI are generated by artificial
              intelligence. While you retain the right to use games you create,
              GameForge AI does not guarantee the uniqueness, functionality, or
              suitability of generated content for any particular purpose.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-neutral-200 mb-3">
              6. Limitation of Liability
            </h2>
            <p>
              GameForge AI is provided &quot;as is&quot; without warranties of
              any kind. We are not liable for any damages arising from your use
              of the service, including but not limited to data loss, service
              interruptions, or inaccuracies in AI-generated content.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-neutral-200 mb-3">
              7. Changes to Terms
            </h2>
            <p>
              We reserve the right to update these terms at any time. Continued
              use of the service after changes constitutes acceptance of the
              revised terms.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-neutral-200 mb-3">
              8. Contact
            </h2>
            <p>
              For questions about these terms, please contact us at{" "}
              <span className="text-primary-light font-medium">
                support@gameforgeai.com
              </span>
              .
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
